import {
  PlayCircle,
  Activity,
  Bell,
  BookOpen,
  Bot,
  Box,
  Bug,
  Building,
  Building2,
  Calendar,
  Car,
  ChartColumn,
  CloudCog,
  Compass,
  Contact,
  CreditCard,
  DatabaseBackup,
  Droplet,
  Eye,
  FileText,
  Filter,
  FlaskConical,
  Gauge,
  Globe,
  Hammer,
  Handshake,
  Headphones,
  House,
  Kanban,
  KeyRound,
  Landmark,
  Languages,
  LayoutDashboard,
  LayoutTemplate,
  Layers,
  Leaf,
  LifeBuoy,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Monitor,
  Network,
  PaintRoller,
  Puzzle,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingCart,
  SmilePlus,
  Snowflake,
  Sofa,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  UserCog,
  Users,
  UtensilsCrossed,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Content registries reference icons by name so config stays serializable (CMS-ready). */
export const icons = {
  activity: Activity,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  box: Box,
  bug: Bug,
  building: Building,
  building2: Building2,
  calendar: Calendar,
  car: Car,
  chart: ChartColumn,
  cloud: CloudCog,
  compass: Compass,
  contact: Contact,
  card: CreditCard,
  backup: DatabaseBackup,
  droplet: Droplet,
  eye: Eye,
  file: FileText,
  filter: Filter,
  flask: FlaskConical,
  gauge: Gauge,
  globe: Globe,
  hammer: Hammer,
  handshake: Handshake,
  headphones: Headphones,
  house: House,
  kanban: Kanban,
  key: KeyRound,
  landmark: Landmark,
  languages: Languages,
  dashboard: LayoutDashboard,
  template: LayoutTemplate,
  layers: Layers,
  leaf: Leaf,
  lifebuoy: LifeBuoy,
  lock: Lock,
  mail: Mail,
  megaphone: Megaphone,
  message: MessageSquare,
  monitor: Monitor,
  network: Network,
  paint: PaintRoller,
  play: PlayCircle,
  puzzle: Puzzle,
  refresh: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  search: Search,
  send: Send,
  server: Server,
  shield: ShieldCheck,
  cart: ShoppingCart,
  smile: SmilePlus,
  snowflake: Snowflake,
  sofa: Sofa,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  target: Target,
  trending: TrendingUp,
  usercog: UserCog,
  users: Users,
  utensils: UtensilsCrossed,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof icons

export function getIcon(name: IconName): LucideIcon {
  return icons[name]
}
